image: node:argon

before_script:
    - apt-get -qq install -y python2.7 python2.7-dev build-essential make gcc g++ libicu-dev
    - apt-get -qq update
    - npm set progress=false
    - npm install --silent

deploy:
    script:
      - npm run build
      - apt-get install -yqq ruby ruby-dev --silent
      - gem install dpl
      - dpl --provider=heroku --app=api-typescript-example --api key=$HEROKU_API_KEY
